# Not currently in use, since we're justing using ClusterIP for private service IP's,
# which nginx-ingress routes to based on subdomain. May find a use for this down the
# road

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: service-ips
  namespace: metallb-system
spec:
  addresses:
  - # list of your private IP pools you want metalLB to manage
  autoAssign: true