# Not currently in use, since we're justing using ClusterIP for private service IP's,
# which nginx-ingress routes to based on subdomain. May find a use for this down the
# road
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-ips
  namespace: metallb-system
spec:
  addresses:
  - # private IP range from your LAN (with subnet CIDR [/32 for single IP])
  autoAssign: true
---
# IP(s) you'll receive traffic into your cluster on
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-entrypoint
  namespace: metallb-system
spec:
  addresses:
  - # your public IP (with /32 CIDR)
  autoAssign: true
